const juegos = [
    {id:1, nombre:"CRASH BANDICOOT 4: IT'S ABOUT TIME", description:"¡Ya era hora de que llegara un juego nuevo de Crash Bandicoot! ¿Habilidades nuevas? Evidentemente. ¿Más personajes jugables? Sep. ¿Dimensiones alternativas? Faltaría más. ¿Jefes alocadísimos? Por supuesto. ¿Cañita de la buena? Por los 'jorts' que lleva que sí. ¿Cómo? ¿Entonces se llaman 'jorts' de verdad? ¡En este universo no!", genero:"aventura", precio:24200, imagen:"img%20videoJuegos/crash-bandicoot-41-02c219941964b437fd16617899407314-640-0.webp"},
    {id:2, nombre:"MARVEL'S SPIDERMAN MILES MORALES", description: "En la última aventura del universo de Spider-Man de Marvel, el adolescente Miles Morales se está adaptando a su nuevo hogar mientras sigue los pasos de su mentor, Peter Parker, como un nuevo Spider-Man. Pero cuando una feroz lucha por el poder amenaza con destruir su nuevo hogar, el aspirante a héroe se da cuenta de que un gran poder conlleva una gran responsabilidad. Para salvar toda la Nueva York de Marvel, Miles debe tomar el manto de Spider-Man y poseerlo.", genero:"aventura", precio:25900, imagen:"img%20videoJuegos/marvels-spiderman1-7f4e9496aad63f7a5a16616492184457-640-0.webp"},
    {id:3, nombre:"GOD OF WAR RAGNAROK", description:"De la mano de Santa Monica Studio llega la secuela del aclamado God of War (2018). Únete a Kratos y Atreus en un viaje mítico en busca de respuestas antes de que llegue el Ragnarök. Juntos, padre e hijo deberán arriesgarlo todo mientras recorren cada uno de los Nueve Reinos. Increíbles paisajes mitológicos serán el escenario de combates contra enemigos temibles, desde dioses nórdicos hasta bestias salvajes, mientras se preparan para el enfrentamiento más importante de sus vidas.", genero:"aventura", precio:40000, imagen:"img%20videoJuegos/god-of-war-ragnarok1-4f98db15c93384992e16676812458120-640-0.webp"},
    {id:4, nombre:"GTA V - GRAND THEFT AUTO V", description:"Los Santos, una extensa y soleada metrópolis llena de gurús de autoayuda, aspirantes a estrellas y famosos en decadencia. En su día la envidia del mundo occidental, lucha ahora por mantenerse a flote en una era de incertidumbre económica y realities baratos.", genero:"aventura", precio:24200, imagen:"img%20videoJuegos/gta-v-grand-theft-auto-v11-ec7ea2a5342c0870d916616535538536-640-0.webp"},
    {id:5, nombre:"FIFA 23", description:"EA SPORTS™ FIFA 23 te trae todo el realismo del deporte rey con la Copa Mundial de la FIFA™ masculina y femenil, la inclusión de equipos de clubes femeniles y nuevas formas de jugar tus modos favoritos.", genero:"deporte", precio:34000, imagen:"img%20videoJuegos/preventa-fifa-231-ae460c1638636c0bbd16615780804847-640-0.webp"},
    {id:6, nombre:"NBA 2K23", description:"Ponte a la altura y desarrolla todo tu potencial en NBA 2K23. Ponte a prueba contra los mejores jugadores del mundo y demuestra tu talento en Mi CARRERA o The W. Une a las estrellas actuales con leyendas eternas en MyTEAM. Construye tu propia dinastía como GM, o dirige la liga en una nueva dirección como Comisionado en Mi NBA. Enfréntate a equipos de la NBA o de la WNBA en JUGAR AHORA y experimenta un juego realista. ¿Cómo Responderás a La Llamada?", genero:"deporte", precio:30500, imagen:"img%20videoJuegos/nba-2k231-24a787d2e82067985c16718022515991-640-0.webp"},
    {id:7, nombre:"CAPTAIN TSUBASA: RISE OF NEW CHAMPIONS", description:"Captain Tsubasa: Rise of New Champions, basado en la amada serie de anime mundialmente, es un juego de fútbol de acción con los últimos gráficos y super jugadas que cualquiera puede disfrutar.", genero:"deporte", precio:30000, imagen:"img%20videoJuegos/captain-tsubasa1-4dab6f6039b28b969f16617901024458-640-0.webp"},
    {id:8, nombre:"UFC 4", description:"Jorge Masvidal encabeza la portada del UFC 4 y se convierte en el primer latino en hacerlo. Date una sacudida en el patio o rodéate de la mítica tradición del kumite; ambas son posibles en las nuevas ubicaciones de UFC 4. Además, combate en UFC Apex y Avenida de la Acción. Tanto si te inspiran los luchadores callejeros como los guerreros de los bajos fondos, tu estilo de combate será moldeado por estos nuevos entornos inmersivos.", genero:"deporte", precio:10500, imagen:"img%20videoJuegos/ufc-41-9fce8af89eabafdfea16614348423293-640-0.webp"},
    {id:9, nombre:"CALL OF DUTY VANGUARDS", description:"Levantate en todos los frentes. En combate aéreo sobre el Pacífico, en lanzamiento aéreo sobre Francia. Defendé Stalingrado con la precisión de un francotirador y atravesá las fuerzas que avanzan en el norte de África. La franquicia Call of Duty® regresa con Call of Duty®: Vanguard, donde los jugadores se verán inmersos en un combate visceral de la Segunda Guerra Mundial a una escala global sin precedentes.", genero:"shooter", precio:33000, imagen:"img%20videoJuegos/call-of-duty-vanguards1-4e710a2ef6bc2dbbf416617913594173-640-0.webp"},
    {id:10, nombre:"CALL OF DUTY MW2", description:"Bienvenido a la nueva era de Call of Duty. Call of Duty: Modern Warfare II sumerge a los jugadores en un conflicto global sin precedentes que presenta el regreso de los icónicos Operadores de Task Force 141. Modern Warfare® II se lanzará con una campaña de trotamundos para un jugador, un combate multijugador inmersivo y una experiencia cooperativa de Spec Ops basada en la narrativa.", genero:"shooter", precio:40000, imagen:"img%20videoJuegos/call-of-duy-mwii1-025333a25235965f7516672729584579-640-0.webp"},
    {id:11, nombre:"CALL OF DUTY: WWII", description:"Call of Duty regresa a sus raíces con Call of Duty: WWII, una experiencia que redefine la Segunda Guerra Mundial para una nueva generación. Desembarca en Normandía el Día D y combate por Europa en algunos de los escenarios más emblemáticos de la guerra más cruenta. Vive el combate clásico de Call of Duty, la camaradería y la naturaleza imperdonable de la guerra contra una potencia global.", genero:"shooter", precio:19500, imagen:"img%20videoJuegos/91pucbdi1bl-_ac_sl1500_1-76e2fe626a1cda3bd815001542753830-640-0.webp"},
    {id:12, nombre:"FALLOUT 76", description:"Es el nuevo videojuego de esta veterana serie de aventuras de rol que nacía de manos de Black Isle, en el año 1997, para posteriormente caer en manos de Bethesda Softworks, los autores de la saga The Elder Scrolls, que han llevado a la franquicia a nuevas cotas de popularidad.", genero:"shooter", precio:10200, imagen:"img%20videoJuegos/fallout-761-1c736d1a0452ed1e8516617845069689-640-0.webp"},
    {id:13, nombre:"MORTAL KOMBAT XL", description:"Incluye el juego principal, y nuevos personajes extranjeros, Leatherface, Triborg, y Bo'Rai Cho. Personajes jugables publicadas anteriormente incluyen Predator, Jason Voorhees, temblor, Tanya, y Goro.También incluye el nuevo paquete de pieles Apocalypse paquete y todos los paquetes de pieles publicadas anteriormente", genero:"lucha", precio:16500, imagen:"img%20videoJuegos/mk-xl-de040e9285aec8326006d3fd7e7b4426-640-0.webp"},
    {id:14, nombre:"DRAGON BALL KAKAROT", description:"Dragon Ball Z Kakarot es un videojuego de rol y acción a cargo de Cyberconnect y Bandai Namco basado en la conocida marca Dragon Ball, que nos propone revivir los mejores momentos de la serie de Akira Toriyama con una gran aventura de rol que incluye, claro, emocionantes combates contra personajes tan icónicos como Vegeta, Raditz o Freezer. De hecho, el arco de Buu se incluirá en el juego.", genero:"lucha", precio:16800, imagen:"img%20videoJuegos/dragon-ball-z-kakarot1-509d04aac339cbd71316215366699307-640-0.webp"},
    {id:15, nombre:"MORTAL KOMBAT 11 ULTIMATE", description:"¡La experiencia MK11 definitiva! Juega como los protectores de la Tierra en las DOS aclamadas historias del juego, donde el tiempo se distorsiona en una lucha para impedir que Kronika regrese el tiempo y reinicie la historia. En esta batalla para salvar la existencia, se ponen a prueba amistades y se forjan nuevas alianzas. MK11 Ultimate cuenta con el reparto completo de 37 luchadores, incluyendo a los recientemente añadidos Rain, Mileena y Rambo. Mortal Kombat 11 muestra con todo detalle cada gracioso Friendship, cada sangriento Fatality y cada devastador Fatal Blow como nunca antes. ¡Estarás tan cerca de la acción que podrás sentirla!", genero:"lucha", precio:21400, imagen:"img%20videoJuegos/mortal-kombat-11-ultimate1-d484d1a7c023b3368b16252447090361-640-0.webp"},
    {id:16, nombre:"MARVEL VS CAPCOM INFINITE", description:"La contienda épica entre dos universos históricos regresa con Marvel vs. Capcom: Infinite. Ultron Sigma quiere erradicar por completo cualquier tipo de vida biológica. Los héroes luchan juntos contra toda posibilidad para derrotar a la más importante amenaza. Su única esperanza yace en las poderosas Gemas del Infinito. 1-2 jugadores. Jugadores en red: 2-8", genero:"lucha", precio:15800, imagen:"img%20videoJuegos/91qqatxvafl-_ac_sl1500_1-4c3ec306413df2715315059283423380-640-0.webp"},
    {id:17, nombre:"GRAN TURISMO 7", description:"Gran Turismo 7 combina las mejores funciones del simulador de conducción real. Si sos piloto competitivo o casual, coleccionista, aficionado a las modificaciones, diseñador de apariencias o fotógrafo, encontrá tu camino con una colección impresionante de modos de juego, incluidos los favoritos de los fanáticos, como Campaña de GT, Arcade y Escuela de manejo.", genero:"carreras-autos", precio:28500, imagen:"img%20videoJuegos/gran-turismo-71-75024740b7270a9f2416616548394864-640-0.webp"},
    {id:18, nombre:"NEED FOR SPEED HEAT", description:"No pares por el día y arriésgalo todo por la noche en Need for Speed Heat, un videojuego de carreras urbanas de Ghost Games y EA en la que el descanso no es una opción. En ese objetivo Need for Speed Heat cuenta con dos partes bien diferencias: con la luz del alba encontramos el Speedhunters Showdown, una competición autorizada donde ganar fondos para personalizar y mejorar los coches de altas prestaciones del garaje; al anochecer la intensidad aumenta con carreras ilegales que aumentan la reputación para poder participar en citas más importantes y cuantiosas en cuanto premios. Todo ello, una vez más, con la policía esperando en cada esquina.", genero:"carreras-autos", precio:16500, imagen:"img%20videoJuegos/need-for-speed-heat1-3717f75ddc631bed2216215518208604-640-0.webp"},
    {id:19, nombre:"THE CREW 2", description:"La nueva entrega de la serie de velocidad de Ubisoft que, en esta ocasión, amplía notablemente su prisma y posibilidades. Con una amplia gama de vehículos, que incluyen motocicletas, lanchas y aviones, el juego mantiene su intención de recrear carreteras casi interminables y reproducirlo todo en un concepto de MMO de carreras y velocidad en el que la conducción no pretende rivalizar con los grandes de la simulación sino ofrecer un acercamiento mucho más arcade. La intención con The Crew 2 es la de llevar la primera parte a un nuevo nivel, no sólo en lo jugable gracias a las mejoras del pilotaje y a la exploración de la tierra, el mar y el aire; sino además a la hora de ofrecer una enorme diversidad en los tipos de escenario dentro de una experiencia de conducción nuevamente ambientada en los Estados Unidos.", genero:"carreras-autos", precio:19000, imagen:"img%20videoJuegos/caratula1-51918f993f3a0bff2a15315126536286-640-0.webp"},
    {id:20, nombre:"F1 22", description:"Entra en la nueva era de la Fórmula 1® en EA SPORTS™ F1® 22, el videojuego oficial de la FIA 2022 Campeonato Mundial de Fórmula Uno™. Tome asiento para una nueva temporada mientras los autos rediseñados y las reglas revisadas redefinen el día de la carrera, pruebe sus habilidades en el nuevo Autódromo Internacional de Miami y pruebe el brillo y el glamour en F1® Life. Compite con los impresionantes autos nuevos de la temporada 2022 de Fórmula 1® con la alineación auténtica de los 20 pilotos y los 10 equipos, y toma el control de tu experiencia de carrera con nuevas secuencias de carrera inmersivas o cinemáticas. Crea un equipo y llévalo al frente de la parrilla con nueva profundidad en el aclamado modo de carrera Mi Equipo, compite cara a cara en pantalla dividida, en multijugador, o cambia el ritmo tomando superdeportivos de algunos de los más grandes del deporte. nombres a la pista.", genero:"carreras-autos-simulación de carreras", precio:32300, imagen:"img%20videoJuegos/fi-221-576531292f4454542216617849011011-640-0.webp"},
    {id:21, nombre:"MINECRAFT STARTER COLLECTION", description:"¡Disfruta de Minecraft! Ahora con un mapa más grande,mejor y más hermoso,además de nuevas formas de jugar y compartir. Este paquete incluye una fantástica compilación de contenidos para explorar todo lo que puedes hacer con Minecraft, entre ellos: el paquete de popurrí de LittleBigPlanet, el paquete de popurrí de mitología griega, el paquete de texturas urbanas y el paquete de skins 1. Además, ¡obtén 700 tokens!", genero:"favoritos", precio:24000, imagen:"img%20videoJuegos/minecraft-starter-collection1-84e0c60bbc69527b7a16616459419965-640-0.webp"},
    {id:22, nombre:"ASSASSIN'S CREED VALHALLA", description:"Conviértete en Eivor, un poderoso saqueador vikingo y lidera a tu clan desde las inclementes costas de Noruega a un nuevo hogar en medio de las exuberantes tierras de cultivo de la Inglaterra del siglo IX. Explora un hermoso y misterioso mundo abierto donde te enfrentarás a brutales enemigos, saquearás fortalezas, construirás el nuevo asentamiento de tu clan y forjarás alianzas para conseguir la gloria y obtener un lugar en el Valhalla. Inglaterra, en la época de los vikingos, es una nación fracturada llena de amos mezquinos y reinos en guerra. Debajo de todo el caos yace una tierra salvaje y llena de abundancia que espera a un nuevo conquistador. ¿Serás tú?", genero:"favoritos", precio:20000, imagen:"img%20videoJuegos/assassins-creed-valhalla1-066936799b301241a116672696338947-640-0.webp"},
    {id:23, nombre:"PLANTS VS ZOMBIES: LA BATALLA DE NEIGHBORVILLE", description:"Propina plantizas en Plant vs. Zombies: Battle for Neighborville, ¡el juego de disparos más disparatado que existe! Desentierra 20 clases de personajes completamente personalizables desde el lanzamiento, en una región social, tres regiones de circulación libre, un modo Operaciones, seis modos multijugador online — incluida una arena de batalla — y mucho más.", genero:"favoritos", precio:11000, imagen:"img%20videoJuegos/plants-vs-zombies1-7ebd04cec0151cf2e116615795171997-640-0.webp"},
    {id:24, nombre:"UNCHARTED THE NATHAN DRAKE COLLECTION", description:"La historia de Nathan Drake comenzó en un barco de pesca frente a la costa de Panamá, y continúa para definir el concepto de aventura. Uncharted: El tesoro de Drake, Uncharted 2: El reino de los ladrones y Uncharted 3: La traición de Drake, tres de los juegos más aclamados de la historia, juntos por primera vez y reconstruidos para PS4. Esto es Uncharted: The Nathan Drake Collection.", genero:"favoritos", precio:4600, imagen:"img%20videoJuegos/uncharted-collection1-1466c7596f99b39afb16614340899462-640-0.webp"}
];

const guardarJuegosLS = (juegos) => {
    localStorage.setItem("juegos", JSON.stringify(juegos));
}

const cargarJuegosLS = () => {
    return JSON.parse(localStorage.getItem("juegos")) || [];
}

guardarJuegosLS(juegos);